Task

Given a positive integer return a value indicating if it is a concatenation of two squares.

This is code-golf the goal is to minimize the size of the source code as measured in bytes.

In [1]:
# Test instance
trueInstances = [11, 90, 1001, 144100, 151296561, 164, 361, 3614, 36144]
falseInstances = [101, 016, 9, 914]

4-element Vector{Int64}:
 101
  16
   9
 914

In [2]:
# Implementation
f(a,s="$a",l=length(s))=0 in[startswith(last(s,l-i),r"0.+")+(parse(Int,last(s,l-i))^.5+parse(Int,first(s,i))^.5)%1 for i in 1:l-1]
f(101)

false

In [3]:
# Create all possible two partitions of a given string while preserving order and each string should not begin with a zero
a="16162200235"
println(parse(Int64,first(a,2))^0.5)
for i in 1:length(a); println(parse(Int64,first(a,i)), " ", last(a, length(a)-i));end
-100^0.5%1==0

4.0
1 6162200235
16 162200235
161 62200235
1616 2200235
16162 200235
161622 00235
1616220 0235
16162200 235
161622002 35
1616220023 5
16162200235 


true

In [4]:
# Testing
for a in trueInstances
    if f(a) != true
        println("FAIL!", a)
    end
end

for a in falseInstances
    if f(a) == true
        println("FAIL!", a)
    end
end

In [5]:
[20, [2,2,2], [3,3,3], [10]]

4-element Vector{Any}:
 20
   [2, 2, 2]
   [3, 3, 3]
   [10]

In [6]:
ceil((2+2+2+3+3+3+10)/3)
20/15

1.3333333333333333

In [7]:
f(i)=i=="dotnet ef"&&print(" "^13,"/\\__\n"," "^7,"---==/    \\\\\n ___  ___   |.    \\|\\ \n| __|| __|  |  )","\\"^7,"\n| _| | _|   \\_/ |  //|\\\n|___||_|       /   \\\\/\\\\")

f (generic function with 3 methods)

In [8]:
f("dotnet ef")

             /\__
       ---==/    \\
 ___  ___   |.    \|\ 
| __|| __|  |  )\\\\\\\
| _| | _|   \_/ |  //|\
|___||_|       /   \\/\\

In [9]:
f(a,s="$a",l=length(s))=0 in[occursin(r"^0.+",last(s,l-i))+(parse(Int,last(s,l-i))^.5+parse(Int,s[1:i])^.5)%1 for i=1:l-1]

f (generic function with 3 methods)

In [10]:
# Testing
for a in trueInstances
    if f(a) != true
        println("FAIL!", a)
    end
end

for a in falseInstances
    if f(a) == true
        println("FAIL!", a)
    end
end

In [237]:
f(n)="hallo"|>foreach((i,j)->print(" "^j,"*"^i," "^(i!=2n-1 ? 2j-3 : 1),"*"^i, "\n"),1:2:2n,n+1:-1:1)

hallo      *         *
     ***       ***
    *****     *****
   *******   *******
  ********* *********


f (generic function with 1 method)

In [236]:
f(5)

MethodError: MethodError: objects of type Nothing are not callable

In [311]:
f(n)=[" "^j*"*"^i for i in 1:2:2n,j in n+1:-1:1]

f (generic function with 3 methods)

In [312]:
f(4)

4×5 Matrix{String}:
 "     *"        "    *"        "   *"        "  *"        " *"
 "     ***"      "    ***"      "   ***"      "  ***"      " ***"
 "     *****"    "    *****"    "   *****"    "  *****"    " *****"
 "     *******"  "    *******"  "   *******"  "  *******"  " *******"

In [214]:
~n=foreach((j,k)->print("$(j%n==0 ? "" : [" "^(k)*"*"^(i)*" "^k for i=1:2:2n][j%n]^(j<n ? 1 : 2)*"\n")"),1:1:2n,2n:-1:1)

~ (generic function with 1 method)

In [216]:
~(5)

          *          
         **         
        ***        
       ****       
     *          *     
    **        **    
   ***      ***   
  ****    ****  


In [248]:
my_array = ["a", "b", "c"]
foreach(j->println(my_array[j]), 1:1:length(my_array))


a
b
c


In [461]:
f(n,i)=n==1 ? i : n%2==0 ? f(n/2,i+=1) : f(n*3+1,i+=1)

f (generic function with 3 methods)

In [485]:
~x=√parse(Int,x)
f(a,s="$a",l=length(s))=0 in[(s[l-i]<'1')+(~last(s,l-i)+~s[1:i])%1 for i=1:l-1]

f (generic function with 3 methods)

In [486]:
println(map(x->f(x),[11, 90, 1001, 144100, 151296561, 164, 361, 3614, 36144, 101, 016, 9, 914]))

Bool[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]


In [487]:
f(i)=i=="dotnet ef"&&print(" "^13,"/\\__
"," "^7,raw"---==/    \\
 ___  ___   |.    \|\ 
| __|| __|  |  )   \\\
| _| | _|   \_/ |  //|\
|___||_|       /   \\/\\
")

f (generic function with 3 methods)

In [488]:
f("dotnet ef")

             /\__
       ---==/    \\
 ___  ___   |.    \|\ 
| __|| __|  |  )   \\\
| _| | _|   \_/ |  //|\
|___||_|       /   \\/\\


In [23]:
f(n)=1 in[i^2+j^2==n&&true for i=0:√n,j=0:√n]

f (generic function with 1 method)

In [15]:
truthy=[0, 1, 2, 4, 5, 8, 9, 10, 13, 16, 17, 18, 20, 25, 26, 29, 32, 34, 36, 37, 40, 41, 45, 49, 50, 52, 53, 58, 61, 64, 65, 68, 72, 73, 74, 80, 81, 82, 85, 89, 90, 97, 98, 100, 101, 104, 106, 109, 113, 116, 117, 121, 122, 125, 128, 130, 136, 137, 144, 145, 146, 148, 149, 153, 157, 160]

66-element Vector{Int64}:
   0
   1
   2
   4
   5
   8
   9
  10
  13
  16
   ⋮
 137
 144
 145
 146
 148
 149
 153
 157
 160

In [24]:
for t in truthy
    if f(t) === false
        print("failed ", t)
    end
end

In [27]:
falsy=[3, 6, 7, 11, 12, 14, 15, 19, 21, 22, 23, 24, 27, 28, 30, 31, 33, 35, 38, 39, 42, 43, 44, 46, 47, 48, 51, 54, 55, 56, 57, 59, 60, 62, 63, 66, 67, 69, 70, 71, 75, 76, 77, 78, 79, 83, 84, 86, 87, 88, 91, 92, 93, 94, 95, 96, 99, 102, 103, 105, 107, 108, 110, 111, 112, 114, 115, 118, 119, 120, 123, 124, 126, 127, 129, 131, 132, 133, 134, 135, 138, 139, 140, 141, 142, 143, 147, 150, 151, 152, 154, 155, 156, 158, 159, 161, 163, 165, 166, 167, 168, 171, 172, 174, 175, 176, 177, 179, 182, 183, 184, 186, 187, 188, 189, 190, 191, 192, 195, 198, 199]

121-element Vector{Int64}:
   3
   6
   7
  11
  12
  14
  15
  19
  21
  22
   ⋮
 187
 188
 189
 190
 191
 192
 195
 198
 199

In [28]:
for t in falsy
    if f(t) === true
        print("failed ", t)
    end
end

In [30]:
using Primes

In [34]:
factor(16)

2^4

In [89]:
f(l,s=length(l),x="and ")="$(l[1]) $(3>s≥2 ? x*l[2] : x*"others") $(s≤1 ? "is" : "are") typing..."

f (generic function with 3 methods)

In [102]:
s="x z typing..."
replace(s,"x"=>"David","z"=>"Alex") 

"David Alex typing..."

In [153]:
f(l,s=length(l))=replace("x z typing...","x"=>l[1],"z"=>"$(s>1 ? "and $(s>2 ? "$(s-1) others" : l[2]) are" : "is")")

f (generic function with 3 methods)

In [161]:
f(l,s=length(l))=replace("x z typing...","x"=>l[1],"z"=>"$(s>1 ? "and $(s>2 ? "$(s-1) others" : l[2]) are" : "is")")

a=["Bubbler"]
b=["no one"]
c=["HyperNeutrino", "user"]
d=["emanresu A", "lyxal", "Jo King"]
e=["pxeger", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"]
g=["10", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"]
h=["and", "are"]
k=["is"]
l=["Bubbler is typing", "is", "are", "and"]

println(f(a))
println(f(b))
println(f(c))
println(f(d))
println(f(e))
println(f(g))
println(f(h))
println(f(k))
println(f(l))

Bubbler is typing...
no one is typing...
HyperNeutrino and user are typing...
emanresu A and 2 others are typing...
pxeger and 10 others are typing...
10 and 10 others are typing...
and and are are typing...
is is typing...
Bubbler is typing and 3 others are typing...


In [ ]:
f(n)=""

In [273]:
|>n

print(" "^13,raw"
            *
           ***  
")

ErrorException: syntax: "|>" is not a unary operator

In [377]:
~n=(i->"*"^i).(1:n).|>println
~(3)

*
**
***


3-element Vector{Nothing}:
 nothing
 nothing
 nothing

In [357]:
~n=(i->"*").(1:n).|>print

~ (generic function with 2 methods)

In [358]:
~(3)

***

3-element Vector{Nothing}:
 nothing
 nothing
 nothing

In [362]:
~x=x^2
y(z)=z^3

l=[~, y]

2-element Vector{Function}:
 ~ (generic function with 2 methods)
 y (generic function with 1 method)

In [356]:
~(3)

3-element Vector{Int64}:
 1
 2
 3

In [402]:
typeof(Int(2.0))

Int64

In [455]:
print("a\n"*"a\n")

a
a


In [113]:
@show [1:10]

[1:10] = UnitRange{Int64}[1:10]


1-element Vector{UnitRange{Int64}}:
 1:10

In [122]:
~n=1 in[i^2+j^2==n for i=0:n,j=0:n]

~ (generic function with 1 method)

In [123]:
~(9997)

true

In [142]:
show([1:10])

UnitRange{Int64}[1:10]

In [ ]:
!l=

In [149]:
test=[1,1,1,1,1,5,1,6,1,1,4,1,0,0,1]

15-element Vector{Int64}:
 1
 1
 1
 1
 1
 5
 1
 6
 1
 1
 4
 1
 0
 0
 1

In [150]:
~l=∑l>0&&

~ (generic function with 1 method)

In [153]:
~l=∑l>(j=0)&&minimum(i->1+!l[1:(j+=1)-i]+!l[j+i:end],l.+1)

~ (generic function with 1 method)

In [160]:
Real(0.0003)-Real(0.0002)

9.999999999999996e-5

In [159]:
Real(0.0002)-Real(0.0001)

0.0001

In [185]:
s="()(())" #[1, 0, 5, 4, 3, 2]

result = [2, 1, 3, 4, 5, 6]

result=zeros(Int, length(s))
for i in 1:length(s)
    c = s[i] 
    if c == ')'
        println(i)
        result[i] = i
    end
    for j in 1:length(s)
        if s[j] == ')' && j>i
            result[i] = j
            break
        end
    end
end
print(result)

1
3
4
[2, 5, 5, 5, 6, 0]

In [177]:
result=collect(1:length(s))

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [378]:
l="\n"
△(n,k)=((i,j)->(" "^(k-j+1)*"*"^i*" "^(k-j))^(n==k ? 2 : 1)).(1:2:2n,1:n)
~n=print(join(△(n,2n),l),l,join(△(n,n),l))
~(1)

  * 
 * *

In [382]:
(1:10)'.|>print

12345678910

1×10 Matrix{Nothing}:
 nothing  nothing  nothing  nothing  …  nothing  nothing  nothing  nothing

In [396]:
print(collect(1:10))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [38]:
s=ceil(π*π)
print((0:s*s)')

[0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 12.0 13.0 14.0 15.0 16.0 17.0 18.0 19.0 20.0 21.0 22.0 23.0 24.0 25.0 26.0 27.0 28.0 29.0 30.0 31.0 32.0 33.0 34.0 35.0 36.0 37.0 38.0 39.0 40.0 41.0 42.0 43.0 44.0 45.0 46.0 47.0 48.0 49.0 50.0 51.0 52.0 53.0 54.0 55.0 56.0 57.0 58.0 59.0 60.0 61.0 62.0 63.0 64.0 65.0 66.0 67.0 68.0 69.0 70.0 71.0 72.0 73.0 74.0 75.0 76.0 77.0 78.0 79.0 80.0 81.0 82.0 83.0 84.0 85.0 86.0 87.0 88.0 89.0 90.0 91.0 92.0 93.0 94.0 95.0 96.0 97.0 98.0 99.0 100.0]

In [30]:
println.(0:0xA*0xA)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


101-element Vector{Nothing}:
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 ⋮
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing

In [47]:
using Combinatorics
test=[[1],[2,3],[2,4],1,4]
collect(powerset([2,3], 1, 1))

2-element Vector{Vector{Int64}}:
 [2]
 [3]

In [55]:
~f=!(0 in(3:length(f).|>i->f[i]==f[i-2]+f[i-1]))

~ (generic function with 1 method)

In [56]:
t1=[1, 1, 2, 3, 5]
t2=[6, 9, 15, 24]
t3=[49, 71, 120, 191, 311, 502]
t4=[3, 4, 7, 11]

f1=[1, 2, 4]
f2=[1, 1, 2, 3, 4]
f3=[3, 4, 6, 8, 9]
f4=[3, 9, 12, 15, 31]

println(typeof(~t1))

println(~t1)
println(~t2)
println(~t3)
println(~t4)


println(~f1)
println(~f2)
println(~f3)
println(~f4)


Bool
true
true
true
true
false
false
false
false
